FROM node:alpine AS builder
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .
RUN yarn build

FROM node:alpine AS server
WORKDIR /usr/src/recruitment
COPY package.json .
COPY package* ./
COPY .sequelizerc .
RUN yarn global add pgtools
RUN yarn install --production
COPY --from=builder ./app/dist ./dist
EXPOSE 4000
CMD ["yarn", "start"]
