import './createCandidateController';
import './getAllCandidatesController';
import './getCandidateByIdController';
import './createTagController';
import './getAllTagsController';
import './searchTagsController';
import './updateTagController';
import './createTechnologyController';
import './getAllTechnologiesController';
